### ISSUE TITLE
Implementar "home"

### ISSUE THREAD

**Issue by unRob** [rodowi/info-bazooka#21]
`GET / HTTP1.1` regresa "Hello world", tal vez deberíamos mostrar ahí la versión?

**Comment by rodowi** [comment]
:+1: 

podría ser un endpoint con los metadatos del proyecto, p.ej.

```json
{
  "version": "0.0.1",
  "docs": "http://docs.infobazooka.apiary.io"
}
```

**Comment by rodowi** [comment]
Relacionado con #26

**Comment by unRob** [comment]
https://github.com/CodeandoMexico/infobazooka/issues/7
